DROP TABLE IF EXISTS `event_%s`;
CREATE TABLE `event_%s` (
 `event_id` int(10) UNSIGNED AUTO_INCREMENT     COMMENT 'primary key' NOT NULL ,
 `user_type` varchar(16) DEFAULT '' COMMENT 'user type'  NOT NULL,
 `user_id` int(10) UNSIGNED     COMMENT 'user id'  NOT NULL,
 `business_type` varchar(64) DEFAULT '' COMMENT 'ip'  NOT NULL,
 `business_id` int(10) UNSIGNED     COMMENT 'business id'  NOT NULL,
 `times` int(10) DEFAULT 0 COMMENT 'times'  NOT NULL,
 `channel` varchar(256) DEFAULT '' COMMENT 'channel'  NOT NULL,
 `ip` char(16) DEFAULT '' COMMENT 'ip'  NOT NULL,
 `device` varchar(32) DEFAULT '' COMMENT 'device'  NOT NULL,
 `device_id` varchar(64) DEFAULT '' COMMENT 'device unique id'  NOT NULL,
 `device_model` varchar(16) DEFAULT '' COMMENT 'device model 5s e.g ...'  NOT NULL,
 `event` varchar(64) DEFAULT '' COMMENT 'event type'  NOT NULL,
 `content` varchar(512) DEFAULT '' COMMENT 'content'  NOT NULL,
 `status` varchar(64) DEFAULT '' COMMENT 'status'  NOT NULL,
 `website` varchar(256) DEFAULT '' COMMENT 'website home url'  NOT NULL,
 `app_id` int(11) UNSIGNED DEFAULT 0 COMMENT 'app id'  NOT NULL,
 `app_version` float(11,2) DEFAULT 0.0 COMMENT 'app version'  NOT NULL,
 `platform` varchar(16) DEFAULT '' COMMENT 'platform'  NOT NULL,
 `os` varchar(16) DEFAULT '' COMMENT 'operation system'  NOT NULL,
 `user_agent` varchar(512) DEFAULT '' COMMENT 'use agent'  NOT NULL,
 `client_version` varchar(64) DEFAULT '' COMMENT 'client os version'  NOT NULL,
 `longitude` double DEFAULT 0.0 COMMENT 'longitude'  NOT NULL,
 `latitude` double DEFAULT 0.0 COMMENT 'latitude'  NOT NULL,
 `network` varchar(16) DEFAULT '' COMMENT 'network'  NOT NULL,
 `simulate` tinyint(1) DEFAULT 0 COMMENT 'is simulate'  NOT NULL,
 `imei` varchar(64) DEFAULT '' COMMENT 'imei'  NOT NULL,
 `bssid` varchar(64) DEFAULT '' COMMENT 'bssi'  NOT NULL,
 `ssid` char(64) DEFAULT '' COMMENT 'ssid'  NOT NULL,
 `idfa` char(64) DEFAULT '' COMMENT 'idfa'  NOT NULL,
 `start_time` bigint(20) DEFAULT 0 COMMENT 'client start time'  NOT NULL,
 `resume_time` bigint(20) DEFAULT 0 COMMENT 'client resume time'  NOT NULL,
 `create_time` bigint(20)  DEFAULT 0  NOT NULL,
 `update_time` bigint(20)  DEFAULT 0  NOT NULL,
PRIMARY KEY (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='event';
